In [0]:
import numpy as np

In [2]:
#Write a function to compute 5/0 and use try/except to catch the exceptions.
try:
  a = int(input())
  b = 5/a

except Exception as e:
  print("In except block %s" %e)


0
In except block division by zero


In [3]:
"""Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]."""

class sentences:
  def __init__(self,subject,verb,objct):
    self.subject = subject
    self.verb =  verb
    self.objct = objct
  
  def generate_sentences(self):
    for i in self.subject:
      for j in self.verb:
        for k in self.objct:
          print(i+" "+j+" "+k)

subject = ["Americans","Indians"]
verb = ["Play","watch"]
objct = ["Baseball","cricket"]
k = sentences(subject,verb,objct)
k.generate_sentences()

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [4]:
"""Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1."""

print("enter the vector by comma seperation")
k = list(map(int,input().split(',')))
N = len(k)
array_1D = np.array(k)
matrix = np.column_stack([array_1D**(N-i-1) for i in range(N)])
print(matrix)

enter the vector by comma seperation
1,2,3,4,5,8
[[    1     1     1     1     1     1]
 [   32    16     8     4     2     1]
 [  243    81    27     9     3     1]
 [ 1024   256    64    16     4     1]
 [ 3125   625   125    25     5     1]
 [32768  4096   512    64     8     1]]
